import cv2



class ImageEnv:
    """
    Environment generated by an picture.
    """

    def __init__(self, 
                 img_path='ENV_PICS/checkerboard.png',
                 reward_weight=1.):
        """
        Args:
            img_path:       Path to an image which encodes a target pattern
            reward_weight:  Reward multiplier
        """
        env_img = cv2.imread(img_path)
        env_img_g = cv2.cvtColor(env_img, cv2.COLOR_BGR2GRAY)
        

