do_train: true

dql_params:
  dql_gamma: 0.99                   
  sync_target_frames: 10000    
  replay_start_size: 10000 
  eps_start: 1.0
  eps_decay: .999985
  eps_min: 0.02
  batch_size: 32
  n_trials: 1000000
  total_rewards_size: 100

lr_params:
  lr: 0.00001
  sched_gamma: 1
  sched_step: 1000

losses:
  l2: 1.
